name: Unzip File

on:
  push:
    branches:
      - main

jobs:
  unzip-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Unzip file
      run: |
        unzip savethedog.zip
        ls -R

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: unzipped-files
        path: /  # Path to the directory containing the unzipped files
